server {
    listen 8080;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        # Trik ini wajib biar sistem routing React kamu nggak error 404
        try_files $uri $uri/ /index.html;
    }
}